server:
  port: 11111
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: register-server
      label: master
      profile: dev
  zipkin:
    locator:
      discovery:
        enabled: true

