spring:
  application:
    name: zipkin-server

server:
  port: 12000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
