server:
  port: 8080
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: general-server
      label: master
      profile: dev
  application:
    name: user-service

feign:
  hystrix:
    enabled: true


